[package]
name = "peacenik"
version = "0.1.0"
authors = ["Tom Parker <palfrey@tevp.net>"]

[dependencies]
log = "*"
env_logger = "0.3"
enum_primitive = "*"
num-traits = "*"

[dependencies.nom]
version = "^2.1"
features = ["verbose-errors"]
